platform :ios, '9.0'

target 'InSearch' do
                
    use_frameworks!

    pod 'Crashlytics'
    pod 'Fabric'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.2'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.1'


    target 'InSearchTests' do
        # Put pods used for both test targets here
        
        target 'InSearchUITests' do
            # Put UI-testing-only pods here
        end
    end

end

                
