platform :ios, '9.0'

target 'InSearch' do
                
    use_frameworks!

    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.2'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.1'
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'iCarousel', '~> 1.8'
    pod 'IQKeyboardManager'
    pod 'Locksmith', '3.0.0'
    pod 'ObjectMapper', '2.2.7'
    pod 'SwiftGen', '4.1.0'
    pod 'SwiftyVK', :git => 'https://github.com/WE-St0r/SwiftyVK.git'
    pod 'Reveal-iOS-SDK', '~> 1.6', :configurations => ['Debug']

    target 'InSearchTests' do
        # Put pods used for both test targets here
    end

end

                
